[package]
name = "lf-pico-template"
version = "0.1.0"
authors = ["gundralaa@berkeley.edu"]
description = "Lingua Franca project template for RP2040 bare metal target platform"

[properties]
# shared properties
# platform = "RP2040"
threading = false

# HelloPico
# Periodically write "Hello, World! to specified stdout
[[app]]
name = "HelloPico"
target = "C"
platform = "RP2040"
main_reactor = "src/HelloPico.lf"
dependencies = {}

[app.properties]
# platform = { name = "RP2040", board = "pico:usb" }

# Blink
# Periodically blink onboard LED and toggle GPIO
[[app]]
name = "Blink"
target = "C"
platform = "RP2040"
main_reactor = "src/Blink.lf"
dependencies = {}

[app.properties]
# platform = { name = "RP2040", board = "pico:usb" }

# Timer
# Periodically print logical and physical time with measured lag
[[app]]
name = "Timer"
target = "C"
platform = "RP2040"
main_reactor = "src/Timer.lf"
dependencies = {}

[app.properties]
# platform = { name = "RP2040", board = "pico:usb" }

# HelloThread
# Periodically print from either core using two workers 
[[app]]
name = "HelloThread"
target = "C"
platform = "RP2040"
main_reactor = "src/HelloThread.lf"
dependencies = {}

[app.properties]
# platform = { name = "RP2040", board = "pico:usb" }

# HelloThreadStatic
# Periodically print from either core using two workers 
[[app]]
name = "HelloThreadStatic"
target = "C"
platform = "RP2040"
main_reactor = "src/HelloThreadStatic.lf"
dependencies = {}

[app.properties]
# platform = { name = "RP2040", board = "pico:usb" }

