name: 'CI'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  find-latest-release:
    uses: lf-lang/lingua-franca/.github/workflows/latest-release.yml@master
    
  check-compile:
    runs-on: ubuntu-latest
    needs: find-latest-release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Java 17
        run: |
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        shell: bash
      - name: Install nix
        run: sudo apt install nix cmake
      - name: Run nix develop
        run: sudo nix develop --extra-experimental-features nix-command --extra-experimental-features flakes
      - uses: lf-lang/action-check-lf-files@main
        with:
          check_mode: "compile"
          no_compile_flag: false
          exclude_dirs: '["failing", "experimental"]'
          compiler_ref: conflict-check-src-only
        #   compiler_ref: ${{ needs.find-latest-release.outputs.ref }}

  check-format:
    runs-on: ubuntu-latest
    needs: find-latest-release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        run: |
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        shell: bash
      - uses: lf-lang/action-check-lf-files@main
        with:
          check_mode: "format"
          exclude_dirs: '["failing", "experimental"]'
          compiler_ref: conflict-check-src-only
        #   compiler_ref: ${{ needs.find-latest-release.outputs.ref }}